### ISSUE TITLE
New feature: syncing module file between local and remote

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#100]
This would help people work with modules. Maybe it could work like this:
(1) user should be able to select any module from remote Ansible
(2) File should be saved locally in temp folder
(3) Editor should be opened, when user presses Ctrl+S file should be uploaded to remote.

**Comment by yungezz** [comment]
@zikalino  thanks for providing the suggestion. Could you pls share full e2e scenario here? like what kind of scenario or task user would like to achieve by doing this? Then we can go to discussion on detail.

**Comment by yungezz** [comment]
checkout latest v0.3.0, we have `ansible.fileCopyConfig` to let user sync local saved files to remote automatically.
