### ISSUE TITLE
[Feature] Enable use custom docker image

### ISSUE THREAD

**Issue by isavl** [VSChina/vscode-ansible#101]
It will be great to add in settings option for configure a custom docker image for "Run Ansible playbook in Docker".

**Comment by yungezz** [comment]
@isavl  thanks for reporting the issue. Actually this feature is enabled. How to use it:
- set configuration item `ansible.terminalInitCommand` to your custom docker run command with your custom docker image, eg `docker run --rm -it -v /xxx/playbooks:/xxx/playbooks --workdir /xxx/playbooks --name mycontainer yourimagename bash`. You need to take care of playbook dir mapping inside docker by yourself.
- run playbook inside docker.
- once docker terminal initialized, type `ansible-playbook /xxx/playbooks/myplaybook.yml` in terminal and run it.

Let us know if met any issue.

**Comment by isavl** [comment]
Ohh thank you very much.
