### ISSUE TITLE
Why do I need cloud credential if I am just running a playbook with non-cloud roles/tasks in a local docker container?

### ISSUE THREAD

**Issue by tchia04** [VSChina/vscode-ansible#102]
## Environment
- Extension version: 
- OS Type: MacOS

## Reproduce steps

* Right click on a playbook.yml file
* Select "Run Ansible Playbook in Docker"

## Expected Results

There should not be any prompt for my cloud credential since the docker is on my local laptop

## Actual Results

I got a pop up dialog with the text "Use cloud credential file /Users/tonyc/.vscode/ansible-credentials.yml" and I have to click on "OK" everytime to close it

Even if I supply my AWS credential in this file, it doesn't seem to use them.

**Comment by yungezz** [comment]
@tchia04 thanks for reporting the issue. Actually you can just ignore that pop up message, To be clear about the problem, even you provide AWS credential info in `/Users/tonyc/.vscode/ansible-credentials.yml`, run ansible playbook in docker isn't picking them?

**Comment by tchia04** [comment]
I have added my AWS credential info in the /Users/tonyc/.vscode/ansible-credentials.yml. However my playbook doesn't have any ec2 tasks/modules.

**Comment by yungezz** [comment]
@tchia04  you don't need to provide cloud credentials if not running cloud modules. just ignore the information message. it's information only.
