### ISSUE TITLE
Snippet is inserted without placeholder support

### ISSUE THREAD

**Issue by moltar** [VSChina/vscode-ansible#104]
## Environment
- Extension version: 0.1.5
- OS Type: MacOS

## Summary
Since the last update, the snippets now work without backspacing. However, the snippet is inserted without placeholder expansion support. It's just a block of text and tabbing through it is impossible.

Demo: http://take.ms/jYpjA

## Reproduce steps

1. Type "yum"
2. Choose `yum_snippet`

## Expected Results

Ability to tab thru the expansion slots

## Actual Results

A block of snippet is inserted but changing placeholders does not work.

**Comment by yungezz** [comment]
@moltar  thanks for reporting the issue. Will look at it and update later.

**Comment by yungezz** [comment]
release in v0.2.6
