### ISSUE TITLE
Enhancement: do not suggest on the task name

### ISSUE THREAD

**Issue by moltar** [VSChina/vscode-ansible#105]
## Environment
- Extension version: 
- OS Type: MacOS

## Summary

Currently, the snippet does not recognize that the cursor is in the `name` portion of the task and provides snippet suggestions in that portion as well. Names should not have any snippet expansion.

## Reproduce steps

1. Type: `- name: yum`
2. Observe snippet list providing suggestions for yum

## Expected Results

While in the `name` keyword, the suggestions should be disabled.

## Actual Results

Suggestions show up.

**Comment by yungezz** [comment]
@moltar  thanks for reporting the issue. Actually we're working on improve auto-completion by detecting authoring context, with that, autocompletion could be more context related. That feature is still under investigation. Stay tuned.

**Comment by prandelicious** [comment]
I also have the same issue. It also gets annoying when the autocomplete pops up in places where you don’t expect any autocomplete then you accidentally select it only to realize it’s the wrong keyword.

**Comment by yungezz** [comment]
release in v0.2.6
