### ISSUE TITLE
Missing files on the target host when using "Run Ansible Playbook remotely via ssh "

### ISSUE THREAD

**Issue by tchia04** [VSChina/vscode-ansible#106]
## Environment
- Extension version: 
- OS Type: Windows

## Summary

When using the "Run Ansible Playbook remotely via ssh ", it seems only the playbook.yml file that was right-clicked on is scp to the target host.  None of the the dependent files such as files stored in the files directory is copied or the inventory folder

## Reproduce steps

a playbook with some tasks that uses the files or template task(not tested)  

## Expected Results

The playbook should run successfully without manually copy the missing files to the target host

## Actual Results

TASK [cert : copy cert] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    /home/XXXXXX/tchia/boscore.pfx
failed: [FOO.EXAMPLE.COM] (item=boscore) => {"changed": false, "dest": "c:\\temp\\", "item": "boscore", "msg": "Could not find or access 'boscore.pfx'\nSearched in:\n\t/home/XXXXX/tchia/Ansible/roles/cert/files/boscore.pfx\n\t/home/XXXX/tchia/Ansible/roles/cert/boscore.pfx\n\t/home/XXXX/tchia/Ansible/roles/cert/tasks/files/boscore.pfx\n\t/home/XXXX/tchia/Ansible/roles/cert/tasks/boscore.pfx\n\t/home/XXXX/tchia/files/boscore.pfx\n\t/home/XXXXX/tchia/boscore.pfx", "src": "boscore.pfx"}
        to retry, use: --limit @/home/XXXX/tchia/Configure_CORE_playbook.retry

PLAY RECAP *********************************************************************
G0DEVBOSCORE01.NEXTESTATE.COM : ok=34   changed=2    unreachable=0    failed=1

My directory structure look like this

playbook.yml
files\boscore.pfx
inventory\dev\hosts
inventory\qa\hosts

I had to manually copy the inventory folder as well as the files folder 

It would great if the Ansible VS extension could copy every files in the same directory the playbook is in as well as some other folders such as inventory/files/template/group_var/ etc to the target host as well. 

Also let us configure what folder on the target host to copy to instead of the home directory.

**Comment by yungezz** [comment]
@tchia04  thanks for reporting this. We're looking at it and will update later.

**Comment by yungezz** [comment]
pls try the latest "copy workspace to remote host" functionality in v0.2.6. let us know if any feedback.

**Comment by tchia04** [comment]
How do I install v0.2.6? The latest version from visual code is 0.1.5.

**Comment by yungezz** [comment]
try restart vscode, or install it from https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible

**Comment by tchia04** [comment]
Never mind. It seems I have the 0.2.6 version installed.  The Changelog was not updated so it still shows 0.1.5 as the latest so I thought I have 0.1.5 installed.

**Comment by yungezz** [comment]
thanks for the reminder, will update changelog.

**Comment by tchia04** [comment]
It seems if the workspace folder is already on the target host then the "copy" process would hang forever with a lot of dots. 

This normally happens during the 2nd execution of "remote ssh" because the first execution of "remote ssh" would create the folder on the target host.  

The workaround is after every "remote ssh" execution I have to manually remove the "workspace" folder so it is ready for the next execution.

**Comment by yungezz** [comment]
thanks @tchia04  for the feedback. I tested the scenario before: copy whole workspace several times by triggering 'remote run via ssh'. but my tested folder is about several migabytes size. will try bigger size of test folder to reproduce the issue. how large is your workspace folder?

**Comment by tchia04** [comment]
It's not that big 14MB. I don't think the size of the folder matter. Is there a way to enable more debugging instead of the ..... so I can see what it's doing?

**Comment by yungezz** [comment]
pls try latest v0.3.0, there's progress bar and error message in output window. let us know if any find there. thanks!
