### ISSUE TITLE
Please allow us to specify the ansible-playbook options when running remotely using ssh

### ISSUE THREAD

**Issue by tchia04** [VSChina/vscode-ansible#107]
## Environment
- Extension version: 
- OS Type: Windows/MacOS

## Summary

Currently when you use the "Run Ansible Playbook remotely using ssh" on a playbook, it execute the following on the target host
ansible-playbook Some_playbook.yml

However I would like to be able to specify some parameters such as -i ./inventory,  --module-path, --extra -vars etc. 

## Actual Results

Perhaps we can store these in the servers.json ?

**Comment by yungezz** [comment]
@tchia04  thanks for reporting the issue, we're looking at it. Customizing command by configuration is good suggestion. We'll evaluate it and update later.

**Comment by yungezz** [comment]
PR #125

**Comment by rkrdo** [comment]
Any updates on this issue? The PR has been merged

**Comment by yungezz** [comment]
@rkrdo  we're working on testing the new release now , which contains lots of new features.  Will release new version of extension in next 2 weeks. Will update here.

**Comment by rkrdo** [comment]
thank you for the fast response @yungezz!

**Comment by anjia0532** [comment]
Any updates on this issue?

**Comment by yungezz** [comment]
released in v0.3.0.  pls try it and let us know if any feedback!
