### ISSUE TITLE
Not able to see code snippets or auto-completion suggestions

### ISSUE THREAD

**Issue by oh4** [VSChina/vscode-ansible#108]
## Environment
- Extension version: 0.0.3
- OS Type: Linux

## Summary
Modded Ansible is not providing syntax highlighting, code snippets with `ctrl + space`, or suggestions as I type. I have VScode installed on Fedora 27 under VScode version 1.21.1. It seems like the module is turned off but it isn't. I have tried disabling and enabling but no luck.

## Reproduce steps
I open a role and select a yaml file such as main.yml within the role and start editing my file but doesn't reflect the extension features of "Modded Ansible" at all.

## Expected Results
When I type or edit, I expect suggestions in key items or module names as they are written. If I press `ctrl + space` after I type a modules name, I expect code snippets but don't ever see any.

## Actual Results
I don't receive any code snippets, no syntax code suggestions or auto completion.

**Comment by oh4** [comment]
I installed **Ansible** and **language-Ansible**, which seems to have fixed the issue. Is this a requirement? Do you need all three for this to work?

Required Extensions:
- Ansible
- language-Ansible
- Modded Ansible

If that's the case, I recommend adding it to the pre-requisites for sure ;). If this is wrong and I should only need **Modded Ansible**, then I guess I'm still doing something wrong or there is a bug somewhere (shrug)

**Comment by yungezz** [comment]
@oh4  thanks for reporting the issue. Our extension has no dependencies to any other extension, you don't need to install them. Pls uninstall `language-Ansible` and `Modded Ansible` extension, then reload `Ansible` extension, and let us know how it works. And, what's version of `Ansible` extension installed on your machine?

**Comment by michalinplus** [comment]
@oh4 You might have some "files.associations" configured to use other extension in specific files, review your workspace or user settings

**Comment by yungezz** [comment]
close it for now.
