### ISSUE TITLE
Syntax highlighting problem

### ISSUE THREAD

**Issue by dmitryzykov** [VSChina/vscode-ansible#112]
## Environment
- Extension version: 0.1.5
- VS code version: 1.22.1
- OS Type: Latest MacOS X

## Summary
Syntax highlighting doesn't work properly.
There is no white color highlighting for values as you show on demo screenshots. 
I have only 2 colors. 

## Reproduce steps
Install vscode-ansible and open any ansible file.

## Expected Results

![authoring](https://user-images.githubusercontent.com/15911918/38566557-a0897430-3cec-11e8-958f-c768b706b288.gif)

## Actual Results

<img width="1152" alt="screen shot 2018-04-10 at 6 15 15 pm" src="https://user-images.githubusercontent.com/15911918/38566570-aacd05f6-3cec-11e8-8fd1-1163c55c92c3.png">

**Comment by dmitryzykov** [comment]
Thank you for pointing to other extensions. 
I went through all of them and disabled one by one and I found the conflicting extension `Jinja`
Without `Jinja` extension syntax highlighting works fine.

**Comment by wholroyd** [comment]
@dmitryzykov Sorry about that issue with my extension. I've been working on an updated version of the extension that should help resolve that in the future.
