### ISSUE TITLE
Document Ansible Version used in Docker Image

### ISSUE THREAD

**Issue by randompixel** [VSChina/vscode-ansible#113]
## Environment
- Docker

## Summary
When using the Ansible inside Docker, and it pulls the default image, it would be useful to show somewhere which version of Ansible is contained in that image. Ubuntu 1604 isn't particularly clear without Googling something and even then you don't know if it has been `apt install ansible` or something else.

Lots of documented Azure functions are new to Ansible 2.5, such as http://docs.ansible.com/ansible/latest/modules/azure_rm_containerregistry_module.html but this isn't available inside the default image that should be pulled.

It should be made clear to users that certain functions won't be available when they try and run the system this way.

Maybe Docker images should be tagged with :2.4, :2.5, :latest rather than the Ubuntu version?

## Reproduce steps
Install Extension
Write play that uses azure_rm_containerregistry
Run via Docker

## Expected Results
Image downloads and play runs

## Actual Results
Image downloads and `ERROR! 'azure_rm_containerregistry' is not a valid attribute for a Play` is thrown.

**Comment by yungezz** [comment]
docker images tag updated and doc updated. pls see https://hub.docker.com/r/microsoft/ansible/tags/.
