### ISSUE TITLE
"Run Ansible Remotely via ssh" doesn't close session

### ISSUE THREAD

**Issue by bbung** [VSChina/vscode-ansible#119]
## Environment
- Extension version: 0.2.6
- OS Type: Windows

## Summary
Remote executing ansible scripts is not closing the sessions after the execution. This results in a endless session stack on the remote machine during development.

## Reproduce steps
1. Create a ansible script
2. setup remote execution with sercers.json file
3. Run Ansible Remotely via ssh
4. connect to executing machine a look for sessions with 'who'

## Expected Results
close each session after execution

## Actual Results
session is not beeing closed

**Comment by bbung** [comment]
Another solution may be to reuse the session as stated in #73

**Comment by yungezz** [comment]
@bbung  thanks for reporting the issue.  Consideration of not closing the ssh session is that let user do custom ssh tasking using this session. Re-use session is under working, will update later.

**Comment by yungezz** [comment]
reuse ssh terminal by settting `ansible.reuseSSHTerminal`. released in v0.3.0,  pls try it and let us know if any feedback.

**Comment by bbung** [comment]
Thank you, works like a charm. I figured a new maybe related issue though #149
