### ISSUE TITLE
[Feature] "Copy Workspace to Remote host?" - "always" or "do not ask again" checkbox

### ISSUE THREAD

**Issue by bbung** [VSChina/vscode-ansible#120]
I am always asked if i want to copy the workspace to the remote host when using "Run Ansible Remotely via ssh" and have to switch from keyboard to my mouse to click on ok. There should be a option to suppress this dialog for exaple a "ok, don't ask again' checkbox/option.

A option in the settings would be sufficient for my usecase.

## Environment
- Extension version: 0.2.6
- OS Type: Windows

## Summary
see above

## Reproduce steps
see #119

**Comment by yungezz** [comment]
thanks for reporting the issue! released in v0.3.0. pls try it and let us know if any feedback!
