### ISSUE TITLE
Can't use ansible snippets in vscode

### ISSUE THREAD

**Issue by jrieken** [VSChina/vscode-ansible#121]
_From @Yannick91 on May 30, 2018 15:54_

Hi,

I am experiencing a weird issue concerning the snippet function of the VScode extension for Ansible.
Normally, when you install the extension and create a new file (yaml) you start typing the beginning of a method it shows you a menu where you can choose to see 'snippets'. However, in my case this is never shown. 

![2018-05-30 17_53_41- main yml - iiams_ansible - visual studio code](https://user-images.githubusercontent.com/39049887/40731925-abf517aa-6421-11e8-9d71-5f865c0cee53.png)

I have reproduced this on another PC, and it works without any other additional configuration. 

----
- VSCode Version: Code 1.18.1 
- OS Version: Windows_NT x64 6.1.7601
- Extensions: 
vscode-ansible|vsc|0.2.6
---

I hope you can take a look at this?

Thanks a lot!

Kind regards,

Yannick

_Copied from original issue: Microsoft/vscode#50810_

**Comment by jrieken** [comment]
can you attach your settings files please?

**Comment by jrieken** [comment]
_From @Yannick91 on May 31, 2018 8:25_

Jrieken,

Thanks for your quick reply. I use the default settings through most of the part of VScode except these following settings I have overwritten:

`{
    "ansible.credentialsFile": "",
    "ansible.credentialsConfigured": true,
    "telemetry.enableTelemetry": false,
    "telemetry.enableCrashReporter": false,
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
    "workbench.colorTheme": "Default High Contrast",
    "window.zoomLevel": 0
}`

The settings of the ansible extension are the following:

`  
  // Command to be run in terminal after it starts
  "ansible.terminalInitCommand": "default",

  // 
  "ansible.credentialsConfigured": false,

  // 
  "ansible.cloudShellConfirmed": false,

  // Enable/Disable hover over on module name
  "ansible.hover": true,

  // Enable/Disable ansible autocompletion
  "ansible.autocompletion": true,`


If you require further info, let me know.

Thanks

**Comment by Yannick91** [comment]
Do you require any additional info for this issue?

**Comment by Yannick91** [comment]
Anyone looking at this thread?

kr,

Yannick

**Comment by akinsbo** [comment]
I am also experiencing this issue

**Comment by Yannick91** [comment]
@mnarusze and where did you change that? As I can't exactly find that config your mentioning.

Thanks

**Comment by Yannick91** [comment]
@mnarusze Thanks for responding this quickly. Just checked it, nothing in there. It is something else I think.

**Comment by mnarusze** [comment]
What is the language mode when you open a YAML file? In my case it's 'YAML'

**Comment by Yannick91** [comment]
All my files in ansible have .YML extension.

**Comment by yungezz** [comment]
HI @jrieken  could you pls try press `ctrl + space` to see if any code snippets showed up?

**Comment by Yannick91** [comment]
Hi @yungezz that doesn't work either the `ctrl + space`

**Comment by Yannick91** [comment]
Thanks for your quick reply.
That doesn't work either. 
I tried to change settings, I re-installed VScode itself, re-installed all plugins...
Nothing seems to work.

**Comment by yungezz** [comment]
PR #155
