### ISSUE TITLE
Document relationship with altenative ansible extension

### ISSUE THREAD

**Issue by ssbarnea** [VSChina/vscode-ansible#122]
Please find a way to document pros and cons of using Microsoft Ansible extension version alternatives, notably https://marketplace.visualstudio.com/items?itemName=haaaad.ansible which apparently has 74k installs, almost double than the 43k on Microsoft one.

Instead of having users confused and maybe even installing both, it would be better to provide enough information on extension mainpage to allow user to make the right decision.

**Comment by yungezz** [comment]
thanks for reporting the issue. we have feature list in install page, maybe could highlight them more.
