### ISSUE TITLE
Remote SSH execution fails if private key has passphrase

### ISSUE THREAD

**Issue by wintermute000** [VSChina/vscode-ansible#126]
## Environment
Win10
Extension 0.2.6

## Summary
Trying to use remote SSH execution with a server that utilizes SSH key with passphrase.
There is nowhere in instructions or config sample JSON to provide passphrase so the SSH fails.
If I try to add a passphrase field in the JSON, it treats it as invalid

## Reproduce steps
Use SSH server that has SSH key + passphrase

Copying c:\Users\xxx\Documents\Untitled-1.yml to xxx.xxx.xxx.xxx..
Failed to copy c:\Users\xxx\Documents\Untitled-1.yml to xxx.xxx.xxx.xxx: scp error: Error: Encrypted private key detected, but no passphrase given

## Expected Results
Remote execution of playbook/copy of workspace via SSH
either prompt for passphrase or allow to store in servers.json

## Actual Results
Configuration  of .ssh/servers.json should have field for passphrase and it should work

[
     {
         "host": "xx.xxx.xxx.xxx",
         "port": 22,
         "user": "xxx",
         "password": "xxx",
         "key": "C:/Users/xxx/xxx/ssh/id_rsa"
     }
]

**Comment by yungezz** [comment]
@wintermute000  thanks for reporting the issue, we're working on fixing. will update later.

**Comment by yungezz** [comment]
fixed in PR #127 , released in v0.3.0. pls have a try and let us know if any other problems.

**Comment by wintermute000** [comment]
how do I used it? I tried to add a passphrase keypair but that didn't do it.

**Comment by wintermute000** [comment]
No matter how I edit C:\user\<user>\.ssh\servers.json, it always reverts back. am I doing anything wrong?

This is in Win10.

**Comment by yungezz** [comment]
are you following "Add New Host" process everytime when "run playbook rermotely via ssh", in the wizard, it will pop up a list with remote hosts in your servers.json, pick it from existing list.

**Comment by yungezz** [comment]
when add new host, type "enter" directly when asking for ssh password, then you'll see input box for key file  path, then passphrase.

![image](https://user-images.githubusercontent.com/37337818/43245843-4f98644c-90e2-11e8-8516-51606b0c321a.png)

**Comment by wintermute000** [comment]
Great, that's clear now, works.
Second problem, how do I specify hosts? normally would run -i hosts...

**Comment by yungezz** [comment]
use configuration item `ansible.customOptions`. pls see more detail in readme.md.

**Comment by wintermute000** [comment]
I tried this e.g. “-i ./hosts”, does nothing. I’ll try reading more
