### ISSUE TITLE
bash errors before command is run

### ISSUE THREAD

**Issue by androbi-com** [VSChina/vscode-ansible#131]
## Environment
- Extension version: 0.2.6
- OS Type: Linux

## Summary
When using "Run Ansible Playbook in Local Ansible" there seems to be some code issued to the shell before the actual ansible command is run.

## Reproduce steps
right click on ansible yml

## Expected Results
just to run the ansible playbook with 
ansible-playbook "myfile.yml"

## Actual Results
user$ export inArray=function (comparer) {
bash: syntax error near unexpected token `('
user$     for (var i = 0; i < this.length; i++) {
bash: syntax error near unexpected token `('
user$         if (comparer(this[i])) return true;
bash: syntax error near unexpected token `this[i]'
user$     }
bash: syntax error near unexpected token `}'
user$     return false;
bash: return: false: numeric argument required
bash: return: can only `return' from a function or sourced script
user$ }
bash: syntax error near unexpected token `}'
user$ export pushIfNotExist=function (element, compare) {
bash: syntax error near unexpected token `('
user$     if (!this.inArray(compare)) {
bash: !this.inArray: event not found
user$         this.push(element);
bash: syntax error near unexpected token `element'
user$     }
bash: syntax error near unexpected token `}'
user$ }
bash: syntax error near unexpected token `}'
user$ ansible-playbook "myfile.yml"

There seem to be two function exports before the command is run, I don't know where this is introduced. Any ideas?

**Comment by yungezz** [comment]
@clausdenk  thanks for reporting the issue, I'm looking at it now. will update if there's finding.

**Comment by yungezz** [comment]
@clausdenk  before ansible-playbook command run in terminal, we export environment variable for telmetry collecting. you can disable it by configuration `telemetrry.enableTelemetry` to false in your `settings.json`.

**Comment by clausdenk** [comment]
@yungez I tried your suggestion, but the error messages remain. Let me know if I can be of any help debugging this.
