### ISSUE TITLE
Defined inventory file in is not used when running local Ansible

### ISSUE THREAD

**Issue by rogerperkin** [VSChina/vscode-ansible#132]
## Environment
- Extension version: 0.2.6
- OS Type: Ubunutu 16.0.4 

## Summary
When running a playbook via Terminal with inventory defined in local ansible.cfg file playbook runs using defined inventory file. 
When using VSC to run playbook locally on Ansible the full path is run e.g 
ansible-playbook "/home/roger/network-programmability/SCRIPTS/Ansible/backup.yml
instead of just backup.yml and fails to pick up defined inventory file, and uses default /etc/ansible/hosts

## Reproduce steps
right click on playbook and specify run playbook on local Ansible 
configure ansible.cfg in local directory
inventory = hosts
configure hosts file in local directory

## Expected Results
I would expect the playbook to run and pick up the defined inventory file, however it fails saying hosts lists is empty and appears to be using default in /etc/ansible 

## Actual Results
roger@ubuntu:~/network-programmability$ ansible-playbook "/home/roger/network-programmability/SCRIPTS/Ansible/backup.yml"
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit
localhost does not match 'all'

**Comment by yungezz** [comment]
@rogerperkin thanks for reporting the issue. When running playbook from local ansible, it will call ansible directly, that's one in path setting.  In your case, you might need to set ansible.cfg path globally, such as in .profile so that every session will read same config file.

**Comment by yungezz** [comment]
close this since it's related to customer environment setting.

**Comment by uocxp** [comment]
One should use in ansible-playbook command the "-i" flag in order to specify the inventory file. Is it possible to configure the extension it to use with the flag "-i" the local hostfile ? It would be very helpful to use different hosts in different projects

**Comment by yungezz** [comment]
you can set custom option to ansible-playbook command by configuration item `ansible.customOptions`.

**Comment by uocxp** [comment]
thanks a lot ^^

**Comment by uocxp** [comment]
is it possible to configure the plugin so when running a playbook from local ansible that ansible run in the playbooks's directory instead of project's directory. That way ansible will pick up the inventory file and the configuration file locally defined in the playbook's project.

**Comment by yungezz** [comment]
maybe the customization could be supported via terminalInitCmd. need investigation.
