### ISSUE TITLE
Custom Docker Image to test Ansible

### ISSUE THREAD

**Issue by mbaquer6** [VSChina/vscode-ansible#135]
## Environment
- Extension version: 0.2.6
- OS Type: Windows/Linux/MacOS

## Summary
Hi,
The Docker image available is an Ubuntu Linux. It would be nice if one can custom a Docker image so one can use the distribution needed (I have my playbooks for CentOS and won't work ie the repositories)

## Reproduce steps
Try a playbook with a rpm repo

## Expected Results
Add a configuration option to select an existing Docker Image.

## Actual Results
Just Ubuntu image is available.

**Comment by yungezz** [comment]
@mbaquer6 could you pls try configuration `ansible.terminalInitCommand` to something like `docker run -it -v /xxxx:/xxxx/ myimage:mytag /bin/bash'?

**Comment by yungezz** [comment]
@mbaquer6  have  you tried the configuration mentioned above? pls let us know if met any problem.  close the issue now  since it's a supported feature.

**Comment by keitalbame** [comment]
@yungezz , I have a similar need and adding the command you mentioned, it only starts the container on a shell, waiting for manual commands
The playbook I selected to run, does not start.
It would be great that the volume would be automatically mounted and the selected playbook run correctly.
