### ISSUE TITLE
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

### ISSUE THREAD

**Issue by shaynecm** [VSChina/vscode-ansible#160]
Failed to upload playbook to Cloud Shell: StorageError: Forbidden

when I am trying to upload a playbook via VS code the shell opens but outputs this error. 

I'm am connected to azure and can run a playbook via git manually which runs fine .

**Comment by yungezz** [comment]
duplicate with #133

**Comment by shaynecm** [comment]
Closing as duplicate
