### ISSUE TITLE
Docker run playbook broken / new variable 

### ISSUE THREAD

**Issue by MrOffline77** [VSChina/vscode-ansible#163]
## Environment
- Extension version: newest
- OS Type: MacOS High Sierra

## Summary
When clicking on `Run Ansible Playbook in Docker `this works fine witch the default `microsoft/ansible:latest` dockerimage. When changing the value `Terminal Init Command` the playbook doesn't start automatically. 
So the Button then is misleading because the Playbook did not start atomically.

To Fix this issue there should be a new variable for the config, to declare the docker image to use, when spinning up the docker container ( `src/constants.ts` ). Then the playbook should be starting automatically like the default `microsoft/ansible:latest` image. 

## Reproduce steps
Click on `Run Ansible Playbook in Docker` when `Terminal Init Command` is not default. 

## Expected Results
Playbook starts automatically with the docker start parameters defined in "Terminal Init Command" and / or with the custom docker image defined on config. 

## Actual Results
Docker container starts, but nothing is happening.

**Comment by yungezz** [comment]
@MrOffline77 thanks for reporting the issue. If user customize `Terminal init command`, whether playbook starts depends on your customization, user may want to reuse a docker instance in  customization or etc, so the extension doesn't  send `ansible-playbook` command to docker terminal today when user customized init command. While I got your scenario here, what you want is just customize docker image, but no change on docker  execution flow. This sounds maybe a new configuration.  We'll discuss it  to see how  to make it general. Stay tuned.

**Comment by MrOffline77** [comment]
@yungezz yes you are right. The ability to change the default image would be great. 
This is a great method for testing playbooks for various OS's. Thank you.

**Comment by yungezz** [comment]
supported in release 0.4.0
