### ISSUE TITLE
not auto-closing quotes and brackets

### ISSUE THREAD

**Issue by chillum** [VSChina/vscode-ansible#165]
## Environment
- Extension version:  0.3.1
- OS Type: Windows

## Summary
built-in YAML mode auto-closes the quotes: when you type in `'`/`"`/`{` it auto-adds the closing quotation mark (I believe, this can be disabled in settings). Ansible mode does not.

## Reproduce steps
* create a file. set mode to YAML.
* enter: `'[right arrow][enter]"[right arrow][enter]{{`
* see:
```yaml
''
""
{{}}
```
* create a file. set mode to Ansible
* enter: `'[right arrow][enter]"[right arrow][enter]{{`
* see the brackets and quotes are not matched:
```yaml
'
"
{{
```
* also note, quoted string is not highlited in Ansible mode (is this really intended?)

## Expected Results

```yaml
''
""
{{}}
```

## Actual Results
```yaml
'
"
{{
```

**Comment by yungezz** [comment]
I'm looking at it now.

**Comment by gavinfish** [comment]
PR #155 should have fixed this issue.

**Comment by yungezz** [comment]
fixed in release 0.4.0.
