### ISSUE TITLE
Nested list of dictionaries not coloring the first key in the dictionary

### ISSUE THREAD

**Issue by evilhamsterman** [VSChina/vscode-ansible#168]
## Environment
- Extension version: 0.3.1
- OS Type: MacOS

## Summary
Nested lists of dictionaries is not highlighting the first key

## Reproduce steps
Create a YAML file with a list of dictionaries at least one level deep

Example
```YAML
children:
  it_users:
  - user_name: test
    user_state: present
```

## Expected Results
user_name should be highlighted/colored the same as user_state in the above example. It works as expected when setting the language to YAML rather than Ansible
![screen shot 2018-09-10 at 4 01 16 pm](https://user-images.githubusercontent.com/59560/45329085-8bd81380-b513-11e8-9aa3-1668477a9239.png)

It also works fine if the list of dictionaries is not nested and the language is set to Ansible
![screen shot 2018-09-10 at 4 01 43 pm](https://user-images.githubusercontent.com/59560/45329103-a7dbb500-b513-11e8-96ff-aa4c2eae8afe.png)

## Actual Results
The first item in the dictionary is not highlighted
![screen shot 2018-09-10 at 4 01 28 pm](https://user-images.githubusercontent.com/59560/45329168-ea9d8d00-b513-11e8-81e8-60f969820b2c.png)

**Comment by yungezz** [comment]
fixed in release 0.4.0.
