### ISSUE TITLE
Invalid syntax highlighting for group module when using variables

### ISSUE THREAD

**Issue by Saltystew** [VSChina/vscode-ansible#211]
## Environment
- Extension version: 0.5.2
- OS Type: Windows

## Summary
If you set a variable or loop for the state or system parameters of the group module it shows the variable as being invalid syntax for those parameters even though it will accept a variable or loop successfully.

## Reproduce steps
Define a basic group section in YML file with name, state, and system parameters.
Use variables/loop for all three parameters.
Name is the only parameter that will show as having valid input.

## Expected Results
I expect it to not show as invalid syntax.

## Actual Results
![image](https://user-images.githubusercontent.com/20447447/51290204-27512780-19d1-11e9-9388-907d41c5bda2.png)
![image](https://user-images.githubusercontent.com/20447447/51290158-0983c280-19d1-11e9-9e01-99ddc1f23ea0.png)

**Comment by yungezz** [comment]
Thanks for reporting. this should come from yaml validation. syntax highlighting will not show warning or error.  will look furthur.

**Comment by Saltystew** [comment]
Oh you're right, I disabled the yaml extension and it goes away. I had completely forgotten I had that extension installed, I assumed it all came from the ansible extension.
