### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by omata** [VSChina/vscode-ansible#212]
- Issue Type: `Performance`
- Extension Name: `vscode-ansible`
- Extension Version: `0.5.2`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by gavinfish** [comment]
Close for duplicating with #205
