### ISSUE TITLE
Support code snippets on custom modules

### ISSUE THREAD

**Issue by murrahjm** [VSChina/vscode-ansible#213]
## Environment
- Extension version: 0.5.2
- OS Type: Windows

## Summary
when writing a playbook and typing out an ansible module name, intellisense will suggest a snippet for the module based on module documentation.  When creating a new module in a local repository folder (library, etc.) intellisense does not suggest a snippet for this new module

## Reproduce steps
1. create a new repo and folder structure in vscode.  create ansible.cfg in the repo:

``` ini
[defaults]
library = ./library
```
2. create a library folder and add module script.
3. ensure "module.py" script has appropriate documentation sections
4. verify ansible-doc command can correctly read the documentation for the new module
5. edit playbook and begin creating a new task for the custom module

## Expected Results
when typing the name of the new module in the playbook, vscode should pop up with auto-complete for the module name and a snippet based on the documentation

## Actual Results
nothing.  No auto-complete information is provided for the custom module

**Comment by yungezz** [comment]
code snippet was generated based on ansible official modules. it's hard to generate code snippet for  local or custom modules because it's not feasible to generate code snippet on the fly.

**Comment by yungezz** [comment]
more words on how code snippets generated: it will ansible-doc to get official doc, then parse it to vscode snippet syntax. if you need it,  pls refer to https://github.com/VSChina/vscode-ansible/blob/master/snippets/readme.md to generate your customized snippets.
