### ISSUE TITLE
Fetch module complains about missing property "path", which has been renamed

### ISSUE THREAD

**Issue by matus-cuper** [VSChina/vscode-ansible#226]
## Environment
- Extension version: 0.5.2
- OS Type: Linux, Ubuntu 18.04.2 LTS

## Summary
I have role which uses fetch module (documentation is here https://docs.ansible.com/ansible/latest/modules/fetch_module.html), where only required fields are dest and src. When I open yaml file with this module, VSCode is complaining about ' Missing property "path" '. The behaviour is the same when I used fetch_snippet generated by this module. I am using Ansible 2.6.3. This issue is similar to #198 , I am getting this error while editing role. Also I tried restart VSCode, but the problem persists. Here is the screenshot of mentioned problem 
![Screenshot from 2019-04-16 12-20-33](https://user-images.githubusercontent.com/19537184/56202214-d342f700-6042-11e9-9353-10119c43191c.png)

## Reproduce steps
Create Ansible role with fetch module with installed VSCode and Ansible extension.

## Expected Results
Fetch module check looks for the "src" and "dest" properties.

## Actual Results
Fetch module check looks only for the "path" property.

**Comment by yungezz** [comment]
HI @matus-cuper  from the hover over information seems you're not using this extension. This extension will only show module doc link like below. and I cannot reproduce the  "path property missing" error.  could you pls share the extension version used? thanks.

![image](https://user-images.githubusercontent.com/37337818/56788116-1f571e00-6831-11e9-93a3-8e18fc33564f.png)

**Comment by kimonoki** [comment]
I have similar problems with fetch and also block. And it looks to me it is caused by YAML extension.

**Comment by matus-cuper** [comment]
Yes, you are both right. The problem was in YAML extension. I created a new issue in YAML extension repo https://github.com/redhat-developer/vscode-yaml/issues/181. Thank you guys!
