### ISSUE TITLE
Outdated properties

### ISSUE THREAD

**Issue by Dovry** [VSChina/vscode-ansible#239]
## Environment
- Extension version: 0.5.2 (latest)
- OS Type: Ubuntu 18.04

## Summary

Ansible has changed some of their flags since (at least) 2.3, The extension reports that 'blockinfile' is missing the 'dest' flag, when this can be found in their documentation [here](https://docs.ansible.com/ansible/2.8/modules/blockinfile_module.html#examples)

`# Before Ansible 2.3, option 'dest' or 'name' was used instead of 'path'`

## Reproduce steps

* Run VScode with the lastest release
* write a .yaml file with [blockinfile](https://docs.ansible.com/ansible/2.8/modules/blockinfile_module.html#synopsis) tasks

## Expected Results

Same as above, except it should not show errors since as of Ansible 2.3 this flag is no longer used. 

## Actual Results

VScode will now clutter the Explorer sidepane and 'Problems' tab with 'missing property "dest"' errors

**Comment by fronczek** [comment]
The same on Windows

**Comment by Dovry** [comment]
@fronczek I'll check it out and verify when I get to work tomorrow.
