### ISSUE TITLE
Need to reload after installing node.js and CloudShell at the first time

### ISSUE THREAD

**Issue by kyliel** [VSChina/vscode-ansible#38]
1. write a test.yml.
2. execute "ansible: run Ansible Playbook in CloudShell"
3. It is my first time to run it. Then I got info to ask me install node.js. After I installed it and came back, run step 2 again. It still asked me install node.js. 
Then I reloaded VSCode. Now I can move to next step.
4. Now I got info "Provisioning Bash in Cloud Shell may take a few seconds.". Then no other information. After minutes, I had no idea what happened. 
Then I reloaded VSCode. Now I can move to next step to connect to CloudShell now. 

Could we tell end users "reload" is needed after installation for node.js and CloudShell? Thank you.

**Comment by yaweiw** [comment]
Isn't that after a new ext is installed VS code will remind you to reload itself?

**Comment by yungez** [comment]
1. for nodejs check, it actually run node.exe to check whether node js is installed. it should not require reload. will take furthur look. and add nodejs as perquisites in document.
2. for provision cloudshell issue, added some status indicator in output panel to show 'Connecting..'

**Comment by yungez** [comment]
fixed by PR #41
