### ISSUE TITLE
issues with running playbook in cloudshell

### ISSUE THREAD

**Issue by yaweiw** [VSChina/vscode-ansible#39]
* User has no idea if cloud shell is set up correctly as no info was given.

* test.yml not uploaded to cloud shell successfully leading to "Error! the playbook: test.yml could not be found"

**Comment by yaweiw** [comment]
@yungez

**Comment by yungez** [comment]
- is fixed by show message 'Connecting..' in output window.
- investigating

**Comment by yungez** [comment]
fixed by PR# 41
