### ISSUE TITLE
issues with running playbook in terminal

### ISSUE THREAD

**Issue by yaweiw** [VSChina/vscode-ansible#40]
PS C:\Work\Projects\temp> docker run --rm -it -v c:\Work\Projects\temp:/temp --workdir /temp --name ansible1513576463467 -e AZURE_CLIENT_ID=your_azure_client_id  -e AZURE_SECRET=your_azure_secret  -e AZURE_SUBSCRIPTION_ID=your_azure_subscription_id  -e AZURE_TENANT=your_azure_tenant_id  -e AWS_ACCESS_KEY_ID=your_aws_access_key_id  -e AWS_SECRET_ACCESS_KEY=your_aws_access_key  -eGCE_EMAIL=your_gce_email  -e GCE_PROJECT=your_gce_project  -e GCE_CREDENTIALS_FILE_PATH=your_gce_credentials_file_path  -e RAX_CREDS_FILE=your_rax_credentials_file_path  -e CLOUDSTACK_DOMAIN=your_cloudstack_domain  -e CLOUDSTACK_ACCOUNT=your_cloudstack_account  -e CLOUDSTACK_PROJECT=your_cloudstack_project  -e CLOUDSTACK_VPC=your_cloudstack_vpc  -e CLOUDSTACK_ZONE=your_cloudstack_zone  microsoft/ansible:ubuntu1604 bashC:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Drive has not been shared.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

**Comment by yaweiw** [comment]
@yungez

**Comment by yungez** [comment]
@yaweiw  this because windows driver where your playbook shared should be shared in docker through docker UI. will update document to add this step.

**Comment by yaweiw** [comment]
@yungez ok configured the drive share in docker. Re-run the command the got below error:
=====
PS C:\Work\Projects\temp> ^Cdocker run --rm -it -v c:\Work\Projects\temp:/temp --workdir /temp --name ansible1513577139864 -e AZURE_CLIENT_ID=your_azure_client_id  -e AZURE_SECRET=your_azure_secret  -e AZURE_SUBSCRIPTION_ID=your_azure_subscription_id  -e AZURE_TENANT=your_azure_tenant_id  -e AWS_ACCESS_KEY_ID=your_aws_access_key_id  -e AWS_SECRET_ACCESS_KEY=your_aws_access_key  -e GCE_EMAIL=your_gce_email  -e GCE_PROJECT=your_gce_project  -e GCE_CREDENTIALS_FILE_PATH=your_gce_credentials_file_path  -e RAX_CREDS_FILE=your_rax_credentials_file_path  -e CLOUDSTACK_DOMAIN=your_cloudstack_domain  -e CLOUDSTACK_ACCOUNT=your_cloudstack_account  -e CLOUDSTACK_PROJECT=your_cloudstack_project  -e CLOUDSTACK_VPC=your_cloudstack_vpc  -e CLOUDSTACK_ZONE=your_cloudstack_zone  microsoft/ansible:ubuntu1604 bash╚docker : The term '╚docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify thatthe path is correct and try again.ources\bin\docker.exe: Error response from daemon: Drive has not been shared.
At line:1 char:1Files\Docker\Docker\Resources\bin\docker.exe run --help'.+ ╚docker run --rm -it -v c:\Work\Projects\temp:/temp --workdir /temp - ...+ ~~~~~~~    + CategoryInfo          : ObjectNotFound: (╚docker:String) [], CommandNotFoundException    + FullyQualifiedErrorId : CommandNotFoundException

Then re-run again and got below error:
===========
PS C:\Work\Projects\temp> docker run --rm -it -v c:\Work\Projects\temp:/temp --workdir /temp --name ansible1513577157568 -e AZURE_CLIENT_ID=your_azure_client_id  -e AZURE_SECRET=your_azure_secret  -e AZURE_SUBSCRIPTION_ID=your_azure_subscription_id  -e AZURE_TENANT=your_azure_tenant_id  -e AWS_ACCESS_KEY_ID=your_aws_access_key_id  -e AWS_SECRET_ACCESS_KEY=your_aws_access_key  -e
GCE_EMAIL=your_gce_email  -e GCE_PROJECT=your_gce_project  -e GCE_CREDENTIALS_FILE_PATH=your_gce_credentials_file_path  -e RAX_CREDS_FILE=your_rax_credentials_file_path  -e CLOUDSTACK_DOMAIN=your_cloudstack_domain  -e CLOUDSTACK_ACCOUNT=your_cloudstack_account  -e CLOUDSTACK_PROJECT=your_cloudstack_project  -e CLOUDSTACK_VPC=your_cloudstack_vpc  -e CLOUDSTACK_ZONE=your_cloudstack_zone  microsoft/ansible:ubuntu1604 bash
Unable to find image 'microsoft/ansible:ubuntu1604' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: pull access denied for microsoft/ansible, repository does not exist or may require 'docker login'.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.

**Comment by yungez** [comment]
fixing
- Doc, add step to share driver to docker
- docker image is private, make it public
