### ISSUE TITLE
CloudShell bash is created for each execution for playbook in CloudShell

### ISSUE THREAD

**Issue by kyliel** [VSChina/vscode-ansible#42]
It seems a new CloudShell bash will be created once I execute "ansilbe: run Ansilbe Playbook in CloudShell". If one CloudShell bash was provisioned at the first time, could I continue to use that one? 
![image](https://user-images.githubusercontent.com/29885760/34091465-ba069926-e3f8-11e7-9a7d-e54832cf859c.png)

Then next time the playbook is directly run on provisioned CloudShell and no need to show below "info" again. 

![image](https://user-images.githubusercontent.com/29885760/34091305-c7946cea-e3f7-11e7-8b3a-e37cfc6f2261.png)

BTW,  could we only show "warn" message at the first time? 
![image](https://user-images.githubusercontent.com/29885760/34091311-dfe721e8-e3f7-11e7-8328-d6a3b74b1809.png)

**Comment by yungez** [comment]
To achieve consistent cloudshell terminal,  need cloudshell sdk supports to get consistent cloudshell connection. otherwise, there's no way to determine whether a cloudshell session is still alive, even vscode terminal could be reused, user will met failure if cloudshell session timedout.

**Comment by yungez** [comment]
and current behavior is aligning with Cloud shell extension behavior in Azure Account. I'm guessing they have same concern when doing this.

**Comment by yungezz** [comment]
PR #94

**Comment by yungezz** [comment]
published in v0.1.5. pls have a try and let us know if any issue. thanks again.
