### ISSUE TITLE
[Doc] Guide end user fill in credentials at the first time to run playbook in cloud

### ISSUE THREAD

**Issue by kyliel** [VSChina/vscode-ansible#51]
At your first time, you need to update your credential file. Any way to remind end users first? For example, directly open the credential file at the first time.

**Comment by yungez** [comment]
the instruction is in doc as below. Is user aware of the instruction, or they met some issue after reading the instruction? directly open credential file seems not a graceful solution, it's confusing when playbook doesn't contain cloud specific modules and user don't want to use ansible extension now although installed.
"c.This step is optinal. If you want to run cloud provider specific Ansible modules, you need set cloud credentials in credential yaml file, default path is $HOME/.vscode/ansible-credentials.yml, or change credential file path by settings item ansible.credentialsFile. Credential file template is at here."

**Comment by yungez** [comment]
fixed by PR #55
