### ISSUE TITLE
Appears to not be working on Windows systems?

### ISSUE THREAD

**Issue by kkolk** [VSChina/vscode-ansible#60]
Running VSCode on Windows none of the syntax highlighting or code completion appears to be working.  Nothing shows up in CTRL+Space for ansible code snippets.

If I do a CTRL+Shift+P I can find the Run Ansible in... commands.   Though if I try to run locally, it immediately fails, I'm guessing since it expects Ansible to not be installed through WSL but instead... through some other unsupported method? 

I'm not too worried about that not working, I can get by just fine with my WSL terminal for playbook execution locally.  But I'm curious what could be interfering with the code snippets/syntax highlighting since that seems really useful.  I've disabled all my other extensions and restarted VSCode without that resolving the issue.

**Comment by kkolk** [comment]
Found the issue, a different module had added values to my settings.xml that prevented this from working.

**Comment by yaweiw** [comment]
@kkolk could you please elaborate a bit more what module had added what values to your settings and lead to the behavior? @yungez maybe it is worth checking?

**Comment by yungez** [comment]
@kkolk  thanks for reporting the issue. currently auto-completion and codesnippet will be triggered when yaml file opened. I'll follow up on this, could you pls share the added values in settings.xml by some other module? Thanks in advance.

**Comment by kkolk** [comment]
[haaaad.ansible](https://marketplace.visualstudio.com/items?itemName=haaaad.ansible)

The directions there have you add these values to the settings.xml:

```
    "files.associations": {
        "**/defaults/**/*": "ansible",
        "**/tasks/**/*.yml" : "ansible",
        "**/handler/*.yml" : "ansible",
        "**/*_vars/**/*.yml" : "ansible",
        "**/roles/**/*.yml" : "ansible",
        "**/playbooks/**/*.yml" : "ansible",
        "**/*ansible*/**/*.yml" : "ansible",
        "**/vars/**/*.yml": "ansible",
        "**/inventory/*/*": "ansible"
    }
```
Removal of that resolved my issue.   Disabling that plugin alone wasn't sufficent.

**Comment by yungez** [comment]
@kkolk thanks for the info, that's due to conflict with [the extension](https://marketplace.visualstudio.com/items?itemName=haaaad.ansible) you mentioned. because both of extension could be triggered by yaml file eventually. the other extension need file association in settings.xml, our extension doesn't need it.
