### ISSUE TITLE
Hover module documentation failures over variable files.

### ISSUE THREAD

**Issue by ichundu** [VSChina/vscode-ansible#63]
Since the latest update (version 0.1.3) I'm getting multiple failures output messages every time I lay the mouse cursor over some text in ansible variable files.
I think this is related to the feature that displays a link to the Ansible module documentation when hovering over a module.

The exact error message I'm getting is:

```
[Error - 8:35:20 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'push' of undefined
  Code: -32603 
```

Also is there a way to disable this feature?

**Comment by yungez** [comment]
@ichundu thanks for reporting the issue, we'll look at it and update later.

**Comment by ichundu** [comment]
@yungez It seems only my windows machine is affected. I'm not able to replicate this on my Linux laptop.
Regards

**Comment by yungez** [comment]
@ichundu  thanks for the update. Actually I tested several variable files, didn't see the error. could you pls share your variable files to help investigate? thanks in advance.
meanwhile, a configuration item #69  will be added to disable hover ability, and in future, more configuration for other language ability to let user customize their own workspace. 

Pls share us any comments/pain point when you use ansible. We'll discuss and investigate to see how to help real ansible user like you by adding more new features to this extension.

**Comment by thomasleveil** [comment]
This error happens when I hover anything from this yml file:

```
MYSQL_DATABASE: bar
MYSQL_USER: bar2
MYSQL_PASSWORD: foo
MYSQL_DATABASE: foo2
```

**Comment by yungez** [comment]
@ichundu  thanks for sharing the info. after investigation, the error happens when yaml file is invalid, such as wrong indent or in your example, duplicate key. Fix here includes:
- provide configuration to enable/disable hover experience
- swallow the error message when hover found invalid yaml file. Reason to swallow it is because hover events happens a lot, we don't want to flush user's output with error message.

Next release contains the fix will be around end of Feb. Stay tuned. Again thanks for feedback.

**Comment by ichundu** [comment]
@yungez you are correct, after some further investigation the issue seems to happen when there is some syntax related error in the yml file. Because the error output is instant and and takes half of the editor workspace it is a deal breaker.
![vscode-ansible](https://user-images.githubusercontent.com/16067816/35945496-b78e7d54-0c60-11e8-8302-e7f5c38dbb5c.png)

Thanks for the fix.

Also the hover feature that displays the module link is very helpful, but it doesn't seem to work in role tasks for me. It's only showing module links on the top level playbook tasks.
Could you also check for this?
Regards

**Comment by yungez** [comment]
@ichundu  currently we only support hover over on modules in tasks. Thanks for suggestion on modules in roles. Will add it and update here once ready.

**Comment by yungez** [comment]
fixed in PR # 69. release in 0.1.4 version.  The config item to enable/disable hover functionality is: 
`ansible.hover`, default value is true.

pls have a try and let us know if any further question. thanks.
