### ISSUE TITLE
Configuring SSH connection

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#66]
So i have tried to run playbook via SSH, with following steps
(1) Selected option "Run playbook via SSH"
(2) I confirmed selected yml file
(3) Extension asked me about SSH host address
(4) I switched windows to copy my VM address from another location
(5) came back to VSC, dialog was closed
(6) I tried to repeat procedure, but it doesn't ask me about my SSH host anymore

I guess my input was cancelled, and that empty input was saved in configuration file, and that's why i am not asked again. I think if user cancels input for some reason, nothing should be updated.

The output is:

Run playbook: c:\dev\playbook.yml
Validate playbook: passed.
Credential file: C:\Users\zikalino\.vscode\ansible-credentials.yml

**Comment by yungez** [comment]
@zikalino  thanks for reporting the issue. The input should be cancel by you click on any other place besides the input box. while will fix if user input nothing, will ask for input again.

**Comment by zikalino** [comment]
well, it's not asking any more...

**Comment by zikalino** [comment]
the content of servers.json is:
[
  null
]
