### ISSUE TITLE
When trying to run playbook via SSH, terminal is started but playbook is not executed

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#72]
Terminal is properly connected, but nothing happens afterwards.

**Comment by zikalino** [comment]
sometimes it works, but sometimes i get just empty terminal:

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

65 packages can be updated.
0 updates are security updates.


*** System restart required ***
Last login: Thu Feb  8 06:04:07 2018 from 167.220.255.24
zim@zims-ubuntu-3:~$

**Comment by yungez** [comment]
@zikalino  I failed to reproduce the issue against my dev box, is the remote server on azure?

**Comment by tonyskidmore** [comment]
I have setup this up to use an SSH server running on Windows 10  Windows Subsystem for Linux (WSL) with Ubuntu 14.04.5 LTS with ansible 2.4.3.0 and I see the same issue.  It runs a terminal but then nothing happens afterwards.

**Comment by yungezz** [comment]
release in v0.2.6
