### ISSUE TITLE
EXTREMELY URGENT: There should be an option to reuse existing terminal

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#73]
Currently when i select for example "Run Ansible Playbook remotely via SSH" it gives me an option, for example:

>23.96.66.61

And it creates new terminal.

I think it would be better to have:

> Existing Terminal: 23.96.66.61
> New connection to: 23.96.66.61

Otherwise it's extremely inconvenient to use, for example if I change anything in my environment what is not preserved, i have to do it again... and again... manually.

That applies also to Docker and Cloudshell.
If people don't want to use existing terminal / docker / cloudshell, they can simply close it and option will disappear.

**Comment by zikalino** [comment]
A good usecase is for example a situation when i need to run a few commands before i can execute playbook (this is when I use Ansible from github repo):

cd ~/ansible
source ./hacking/env-setup

if this command is not executed in current shell, i will get:

zim@zims-ubuntu-3:~$ ansible-playbook ./cloud-config-azure.yml
The program 'ansible-playbook' is currently not installed. You can install it by typing:
sudo apt install ansible
zim@zims-ubuntu-3:~$

That's why i think it's extremely important to give control to the user how, and which terminal is used.

**Comment by yungez** [comment]
reuse ssh terminal looks nice. but for docker, let's think it over.

**Comment by yungezz** [comment]
released in v0.3.0.
