### ISSUE TITLE
Need help with the Setup

### ISSUE THREAD

**Issue by rmauc** [VSChina/vscode-ansible#82]
Hi 

I am very interested in using this extension ... could you help me with the setup or use this as feedback to update the readme? The comments in bold are my questions.. Thanks!

Run Playbook Remotely via ssh

Configure your remote server in $HOME/.ssh/server.json like below. Or follow wizard to fill in server information. **Where does this file go? On the remote server? (the path has forward slashes - so it must be on the Ansible Linux machine? If its local - can you provide the default path?** 
[
     {
         "host": "your host",
         "port": 22,
         "user": "your user name",
         "password": "your ssh password",
         "key": "your private key"
     }
]
Configuration
This extension provides 2 configurations in settings.json. **I assume we create this file. What is the default location here?**
ansible.credentialsFile
This configuration is used to specify ansible credentials file path. Default is $HOME/.vscode/ansible-credentials.yml.
ansible.termininalInitCommand
This configuration is used to specify customized terminal init command. Default is docker run commands for docker, and 'ansible-playbook' for local setup.

**Comment by rmauc** [comment]
Could you add an example settings.json file - so we know the correct format
Thanks!

**Comment by yungez** [comment]
@rmauc  thanks for reporting the issue. Here's detail setup steps on setting remote ssh run.
1. $HOME/.ssh/server.json, this file in on your host machine, where vscode is running, not remote server.

2. `ansible.credentialsFile` will be created automatically, default location is  $HOME/.vscode/ansible-credentials.yml of your host machine, where vscode is running, not remote server.

hope this helps.  Feel free to ping us if any furthur question.

**Comment by yungezz** [comment]
@rmauc  HI, is this still an issue for you? does above instruction and readme doc helps?

**Comment by yungezz** [comment]
@rmauc  we'd like to close the issue for now, pls reopen the issue or create new one if you met any issue to run playbook via ssh by following the doc, or any feedback on user experience. thanks.
