### ISSUE TITLE
Unable to parse Symbols: invalid yaml file.

### ISSUE THREAD

**Issue by kkolk** [VSChina/vscode-ansible#86]
The plugin starts outputting this constantly to the Output tab as soon as I start typing a new line into the playbook.   Which of course the yaml isn't valid when a line is only partially typed in.

Again like the similar messages in the previous version, this switches me constantly away from the terminal tab to output, which is frustrating.

**Comment by yaweiw** [comment]
@yungez

**Comment by yungez** [comment]
@kkolk  thanks for reporting the issue. the issue will be fixed in next release, will update status here.

**Comment by yungez** [comment]
@kkolk  by second check, the error msg only shows when user tried click `ctrl + space + O` to show symbols. Could you pls share repo steps to help investigation? how could the error switch focus from terminal tab to output? suppose you should editing in text window. Thanks in advance!

**Comment by kkolk** [comment]
I'll try to recreate it, the same file that did it yesterday didn't do it for me today.

Basically it was a larger step like this one (this actual step in fact):

`  - name: Windows | Create VM from template {{ win_vm_template }}
    when: create_vm and guest_os == "Windows"
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: "{{ domain_admin_user }}"
      password: "{{ domain_admin_pass }}"
      datacenter: Default
      name: "{{ inventory_hostname | regex_search('([^.]*)') }}"
      cluster: "{{ vm_cluster }}"
      resource_pool: "{{ vm_resource_pool }}"
      state: poweredon
      template: "{{ win_vm_template }}"
      folder: "{{ vm_folder }}"
      disk:
        - size_gb: 100
          type: thin
          datastore: "{{ datastore }}"
      networks:
        - name: "{{ vm_network }}"
          ip: "{{ ipv4addr }}"
          gateway: "{{ vm_gateway }}"
          netmask: "{{ vm_netmask }}"
      hardware:
        memory_mb: "{{ vm_memory | default(4096) }}"
      customization:
        fullname: "Operations"
        orgname: "MyCompany"
        dns_servers:
          - "{{ dnsserver1 }}"
          - "{{ dnsserver2 }}"
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\admin\scripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
        autologon: yes
        autologoncount: 1
        password: "{{ default_local_password }}"
    delegate_to: localhost
`

Under hardware: I went to add a CPU count to change it to this:

`  - name: Windows | Create VM from template {{ win_vm_template }}
    when: create_vm and guest_os == "Windows"
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter_hostname }}"
      username: "{{ domain_admin_user }}"
      password: "{{ domain_admin_pass }}"
      datacenter: Default
      name: "{{ inventory_hostname | regex_search('([^.]*)') }}"
      cluster: "{{ vm_cluster }}"
      resource_pool: "{{ vm_resource_pool }}"
      state: poweredon
      template: "{{ win_vm_template }}"
      folder: "{{ vm_folder }}"
      disk:
        - size_gb: 100
          type: thin
          datastore: "{{ datastore }}"
      networks:
        - name: "{{ vm_network }}"
          ip: "{{ ipv4addr }}"
          gateway: "{{ vm_gateway }}"
          netmask: "{{ vm_netmask }}"
      hardware:
        memory_mb: "{{ vm_memory | default(4096) }}"
        num_cpus: "{{ vm_cpus | default(1) }}"
      customization:
        fullname: "Operations"
        orgname: "MyCompany"
        dns_servers:
          - "{{ dnsserver1 }}"
          - "{{ dnsserver2 }}"
        runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\admin\scripts\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
        autologon: yes
        autologoncount: 1
        password: "{{ default_local_password }}"
    delegate_to: localhost
`

As soon as num_cpus:  was entered followed by space, the messages started appearing.

**Comment by yungezz** [comment]
published in v0.1.5. pls have a try and let us know if any issue. thanks again.
