### ISSUE TITLE
Hover tooltips not displayed in ansible Role structure

### ISSUE THREAD

**Issue by zswanson** [VSChina/vscode-ansible#88]
## Environment
- Extension version: 0.1.4
- OS Type: Windows 7

## Summary
Hover tooltips only display when using an 'all in-one playbook'

## Reproduce steps
Create a yml file that includes keys for: hosts, vars, tasks, etc. Should be able to hover mouse over a module name and see a link to the documentation. 
![image](https://user-images.githubusercontent.com/1272954/36881276-3fe987e8-1d9b-11e8-8084-735c2c801a43.png)

Create an ansible role structure (or import an ansible-galaxy role) and none of the hover tooltips display for invoked modules in the tasks/handlers yaml files.
![image](https://user-images.githubusercontent.com/1272954/36881370-b9dfbfcc-1d9b-11e8-80ca-5103168f022d.png)

**Comment by yungez** [comment]
@zswanson  thanks for reporting the issue. Currently hover over tips not supported in role file. Will update here if any progress. thanks.

**Comment by yungezz** [comment]
published in v0.1.5. pls have a try and let us know if any issue. thanks again.
