### ISSUE TITLE
Snippets only show up after backspacing

### ISSUE THREAD

**Issue by moltar** [VSChina/vscode-ansible#90]
## Environment
- Extension version: latest
- OS Type: MacOS

## Summary
The snippet suggestion only shows up after hitting a backspace.

Demo: http://take.ms/PyddN

## Reproduce steps
1. Create a new playbook
2. Start typing "yum" and observe that no snippets are showing up in suggestions
3. When you type letter "m", then hit "backspace" key
4. You will now see snippets in the list

## Expected Results
To see snippets right away together with the completion results.

## Actual Results
No snippets are showing up.

**Comment by yaweiw** [comment]
@yungez

**Comment by yungez** [comment]
@moltar  thanks for reporting the issue. Code snippet is showed after click `Ctrl + Space`, this is vscode behavior, please refer to [detail](https://code.visualstudio.com/docs/editor/userdefinedsnippets) here. Typing `yum`, showed auto-completion. Please let us know any other feedback.

**Comment by moltar** [comment]
Right, but if you enable:

>     "editor.snippetSuggestions": "top",

Shouldn't they show up with the rest of the suggestions?

I have JS snippets show up without having to hit Ctrl + Space.

**Comment by moltar** [comment]
Here is a demo on a fresh copy of VSC: http://take.ms/2B4ib

Launched with:

> code -n --user-data-dir=/tmp --extensions-dir=/tmp

**Comment by hooksie1** [comment]
I'm seeing the same thing on Fedora 27.

**Comment by yungez** [comment]
thanks for share the info. we're looking at the issue, will update here later.

**Comment by yungezz** [comment]
Thanks.  published in v0.1.5. pls have a try and let us know if any furthur issue.
