### ISSUE TITLE
+New Host option when running playbook via SSH

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#96]
## Environment
Any

## Summary
When running playbook remotely via SSH and selecting host it would be nice to have **+ New host** option.
I just needed to configure new host today, and my first thought was "where is the configuration file". As i didn't remember that and was in hurry i just ended up using command line.
So that would be pretty useful.

**Comment by yungezz** [comment]
@zikalino that's great idea. will add it later.

**Comment by yungezz** [comment]
fixed in PR #99 , released in v0.1.5
